# Generated by Django 5.0.4 on 2024-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentmodel_got_recommended_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymentmodel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
