# Generated by Django 5.0.4 on 2024-07-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentpaymentmodel_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalarypaymentmodel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
