# Generated by Django 5.0.4 on 2024-07-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staffusersalarymodel_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffusersalarymodel',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
