# Generated by Django 5.0.4 on 2024-07-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_staffusersalarymodel_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('female@#', 'Female'), ('male@#', 'Male')], max_length=20, null=True),
        ),
    ]
