# Generated by Django 5.0.4 on 2024-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('female_user', 'Female'), ('male_user', 'Male')], max_length=20, null=True),
        ),
    ]
