from django.contrib import admin
from .models import *
admin.site.register(UserModel)
admin.site.register(BranchModel)
admin.site.register(RoomModel)
admin.site.register(DiscountModel)
admin.site.register(AdvertisementModel)
admin.site.register(LessonModel)
admin.site.register(StudentModel)
admin.site.register(TeacherModel)
admin.site.register(StaffUserModel)
admin.site.register(GroupModel)
admin.site.register(AbsenceModel)
admin.site.register(GroupScheduleModel)
admin.site.register(StudentPaymentModel)
admin.site.register(TeacherSalaryPaymentModel)
admin.site.register(StaffUserSalaryModel)    
admin.site.register(NewStudentFormModel)
admin.site.register(ExpenseModel)
